# Generated by Django 5.0.7 on 2024-07-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="products",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
