# Generated by Django 5.0.7 on 2024-07-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_account_list_delete_shoppinglist_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
