# Generated by Django 5.0.7 on 2024-07-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_account_email_remove_account_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="zip_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
