# Generated by Django 5.0.7 on 2024-07-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_account_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
